#!/bin/sh
# preinst script for gbiblio-client
#
# see: dh_installdeb(1)

set -e

# Adding user 'cau'
adduser cau --disabled-password --gecos cau
chpasswd -m <<EOF
cau:r3pl1c4nt3
EOF

# Adding group 'admin'
addgroup admin


exit 0


