#!/bin/bash

rm -rf /usr/lib/thunderbird/chrome/en-US.jar
dpkg-divert --package gbiblio-server --rename --quiet --remove /usr/lib/thunderbird/chrome/en-US.jar

rm -rf /usr/share/applications/seamonkey.desktop
dpkg-divert --package gbiblio-server --rename --quiet --remove /usr/share/applications/seamonkey.desktop

