#!/bin/sh

set -e

#DEBHELPER#

if [ remove = "$1" ]; then
    rm -f /usr/lib/ubiquity/ubiquity/frontend/__init__.py 
    dpkg-divert --package gbiblio-ubiquity --remove --rename \
             --divert /usr/lib/ubiquity/ubiquity/frontend/__init__.py.real /usr/lib/ubiquity/ubiquity/frontend/__init__.py

    rm -f /lib/partman/recipes/20guadalinex 
    dpkg-divert --package gbiblio-ubiquity --remove --rename \
             --divert /lib/partman/recipes/20guadalinex.py.real /lib/partman/recipes/20guadalinex
fi



