#!/bin/sh

set -e

#DEBHELPER#

if [ remove = "$1" ]; then
    rm -f /usr/lib/ubiquity/ubiquity/frontend/__init__.py 
    dpkg-divert --package gbiblio-ubiquity --remove --rename \
             --divert /usr/lib/ubiquity/ubiquity/frontend/__init__.py.real /usr/lib/ubiquity/ubiquity/frontend/__init__.py

    rm -f /lib/partman/recipes/20guadalinex 
    dpkg-divert --package gbiblio-ubiquity --remove --rename \
             --divert /lib/partman/recipes/20guadalinex.real /lib/partman/recipes/20guadalinex

    rm -f /lib/partman/automatically_partition/20some_device 
    dpkg-divert --package gbiblio-ubiquity --remove --rename \
             --divert /lib/partman/automatically_partition/20some_device.real /lib/partman/automatically_partition/20some_device
fi



