#!/bin/sh
# preinst script for gbiblio-client
#
# see: dh_installdeb(1)

set -e

# Adding user 'cau'
adduser cau --disabled-password --gecos cau
chpasswd -m <<EOF
cau:bl4d3runner
EOF

# Adding group 'admin'
addgroup admin


exit 0


