#!/bin/sh
# preinst script for gbiblio-client
#
# see: dh_installdeb(1)

set -e

# Adding user biblio:
if [ "`cat /etc/passwd|awk 'BEGIN{FS=":"};{print $1}'|grep biblio`" != "biblio" ]; then
  echo "adding user biblio ..."
  adduser biblio --disabled-password --gecos biblio
fi

# Adding user cau:
if [ "`cat /etc/passwd|awk 'BEGIN{FS=":"};{print $1}'|grep cau`" != "cau" ]; then
  echo "adding user cau ..."
  adduser cau --disabled-password --gecos cau
fi

# Adding group admin:
if [ "`cat /etc/group|awk 'BEGIN{FS=":"};{print $1}'| grep -v lpadmin|grep admin`" != "admin" ]; then
  echo "adding group admin ..."
  addgroup admin
fi

exit 0
