# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1223653505);
user_pref("app.update.lastUpdateTime.background-update-timer", 1223653501);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1223653501);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1223653505);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1223653506);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("extensions.enabledItems", "langpack-es-AR@firefox-3.0.ubuntu.com:3.0.1,langpack-es-ES@firefox-3.0.ubuntu.com:3.0.1,{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}:0.7.2,guadafox@guadalinex.org:0.1,langpack-es-AR@xulrunner-1.9.ubuntu.com:1.9.0.1,langpack-es-ES@xulrunner-1.9.ubuntu.com:1.9.0.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.1");
user_pref("extensions.lastAppVersion", "3.0.1");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1226245510);
