#!/bin/bash


MEDUSA_CONF=/etc/medusa.conf

rm $MEDUSA_CONF

if [ "$(whoami)" != "root" ]; then
	exit 1
fi

echo '<!DOCTYPE Test>
<configuration>
 <workstation_list>' > $MEDUSA_CONF

for x in $(seq 1 20)
do
  CLIENT="/etc/dhcp3/mac_cliente$x.conf"
  MAC=$(cat $CLIENT | grep hardware | sed -e 's/   hardware ethernet //g' | sed -e 's/;//g')
  if [ "$MAC" != "00:00:00:00:00:00" ]; then
    if [[ "$MAC" =~ "[1234567890abcdefABCDEF][1234567890abcdefABCDEF]:[1234567890abcdefABCDEF][1234567890abcdefABCDEF]:[1234567890abcdefABCDEF][1234567890abcdefABCDEF]:[1234567890abcdefABCDEF][1234567890abcdefABCDEF]:[1234567890abcdefABCDEF][1234567890abcdefABCDEF]:[1234567890abcdefABCDEF][1234567890abcdefABCDEF]" ]]; then
    # cliente-x -> 172.26.1.(x + 9)
    echo "  <workstation ip="\"172.26.1.$(expr $x + 9)\"" >
     <hostname>cliente-$x</hostname>
     <mac>$MAC</mac>
    </workstation>" >> $MEDUSA_CONF
    fi
  fi
done

echo ' </workstation_list>
 <session>
  <initial_time seconds="3600" />
 </session>
</configuration>' >> $MEDUSA_CONF

