#!/bin/sh
# postinst script for gbiblio-server
#
# see: dh_installdeb(1)

set -e

# Diverts

dpkg-divert --package gbiblio-server --rename --quiet --add /etc/exports
ln -fs /etc/exports.gbv5 /etc/exports

dpkg-divert --package gbiblio-server --rename --quiet --add /etc/update-exim4.conf.conf
ln -fs /etc/update-exim4.conf.conf.gbv5 /etc/update-exim4.conf.conf

# Exports directories creation
[ ! -d /var/nfs/compartido ] && mkdir -p /var/nfs/compartido
[ -d /var/nfs/compartido ] && chmod 1777 /var/nfs/compartido

# Change owner of id_rsa
chown cau:cau /home/cau/.ssh/id_rsa

# Adding /etc/sudoers
cat << EOF > /etc/sudoers
# /etc/sudoers
#
# This file MUST be edited with the 'visudo' command as root.
#
# See the man page for details on how to write a sudoers file.
#

Defaults        env_reset

# Host alias specification

# User alias specification

# Cmnd alias specification

Cmnd_Alias  BIBLIOADMIN = /usr/sbin/mdserver, /usr/bin/system-config-printer, /usr/sbin/gbiblio-ine-selector

Cmnd_Alias  BIBLIOADMINNOPW = /sbin/halt, /etc/init.d/cupsys

# User privilege specification
root    ALL=(ALL) ALL

# Uncomment to allow members of group sudo to not need a password
# (Note that later entries override this, so you might need to move
# it further down)
# %sudo ALL=NOPASSWD: ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Permisos de biblio
biblio ALL = NOPASSWD: BIBLIOADMINNOPW, PASSWD: BIBLIOADMIN
EOF


# Permissions in /etc/sudoers

chown root.root /etc/sudoers
chmod 440 /etc/sudoers

# Adding cau to admin's group

usermod -G admin cau

# Adding biblio to lpadmin's group

usermod -G lpadmin biblio

# Added biblio_arranque.sh to runlevels 2 3 4 5

chmod 755 /etc/init.d/biblio_arranque.sh
update-rc.d biblio_arranque.sh start 98 2 3 4 5 .

# INTERFACE=$(awk -F: '/:/ {print $1}' /proc/net/dev | egrep -v "lo|wm|wl")

cat << EOF > /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
   address 192.168.1.10
   netmask 255.255.255.0
EOF
 
# Removing /etc/ssh/sshd_not_to_be_run

if [ -f /etc/ssh/sshd_not_to_be_run ]; then
  rm /etc/ssh/sshd_not_to_be_run -f
fi

# Added hosts and hostname workaround

cat > /etc/hosts <<EOF
127.0.0.1       localhost
192.168.1.10    servidor
192.168.1.11    cliente-1
192.168.1.12    cliente-2
192.168.1.13    cliente-3
192.168.1.14    cliente-4
192.168.1.15    cliente-5
192.168.1.16    cliente-6
192.168.1.17    cliente-7
192.168.1.18    cliente-8
192.168.1.19    cliente-9
192.168.1.20    cliente-10
192.168.1.21    cliente-11
192.168.1.22    cliente-12
192.168.1.23    cliente-13
192.168.1.24    cliente-14
192.168.1.25    cliente-15
192.168.1.26    cliente-16
192.168.1.27    cliente-17
192.168.1.28    cliente-18
192.168.1.29    cliente-19
192.168.1.30    cliente-20

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
EOF

echo "servidor" > /etc/hostname
hostname --file /etc/hostname

exit 0


