#!/bin/bash
#
# Fichero: update-net-config
# 
# Éste fichero forma parte del Configurador de red para Guadalinex V5 Bibliotecas, gbiblio-net-config.
# Su cometido es cambiar la configuración de red actualizando el fichero /etc/network/interfaces
#
#

WINTERFACE="$(awk -F: '/:/ {gsub(" ","",$1); print $1}' /proc/net/wireless)"

if [ "$1" == "eth0" ];then
    ifconfig $WINTERFACE down
    cat <<EOF > /tmp/interfaces
auto lo
iface lo inet loopback

auto $1
iface $1 inet static
        address 192.168.1.10
        netmask 255.255.255.0
        gateway 192.168.1.1
EOF
else
    ifconfig eth0 down
    cat <<EOF > /tmp/interfaces
auto lo
iface lo inet loopback

auto $WINTERFACE
iface $WINTERFACE inet static
        address 192.168.1.10
        netmask 255.255.255.0
        gateway 192.168.1.1
        wireless-essid biblioteca
        wireless-key s:1357986420900
EOF

fi

cp /tmp/interfaces /etc/network/interfaces
/etc/init.d/networking restart
